name 'cocoon'
maintainer 'FullStack'
maintainer_email 'team@gofullstack.com'
license 'MIT'
description 'Installs/Configures a Rails development box.'
long_description 'Installs/Configures a Rails development box.'
version '0.1.1'
